# Generated by Django 5.2.11 on 2026-03-04 19:51

from django.db import migrations, models


def migrate_planning_to_planned(apps, schema_editor):
    """Update all 'Planning' status values to 'Planned'."""
    models_to_update = [
        'anime', 'basicmedia', 'boardgame', 'book', 'comic', 'game',
        'historicalanime', 'historicalbasicmedia', 'historicalboardgame', 
        'historicalbook', 'historicalcomic', 'historicalgame', 'historicalmanga',
        'historicalmovie', 'historicalseason', 'historicaltv',
        'manga', 'movie', 'season', 'tv'
    ]
    
    for model_name in models_to_update:
        try:
            Model = apps.get_model('app', model_name)
            Model.objects.filter(status='Planning').update(status='Planned')
        except LookupError:
            # Model doesn't exist, skip it
            pass


def reverse_planned_to_planning(apps, schema_editor):
    """Reverse: change 'Planned' back to 'Planning'."""
    models_to_update = [
        'anime', 'basicmedia', 'boardgame', 'book', 'comic', 'game',
        'historicalanime', 'historicalbasicmedia', 'historicalboardgame', 
        'historicalbook', 'historicalcomic', 'historicalgame', 'historicalmanga',
        'historicalmovie', 'historicalseason', 'historicaltv',
        'manga', 'movie', 'season', 'tv'
    ]
    
    for model_name in models_to_update:
        try:
            Model = apps.get_model('app', model_name)
            Model.objects.filter(status='Planned').update(status='Planning')
        except LookupError:
            pass


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0055_alter_item_media_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anime",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="basicmedia",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="comic",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalanime",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbasicmedia",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalboardgame",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbook",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalcomic",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgame",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmanga",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmovie",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalseason",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicaltv",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="manga",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tv",
            name="status",
            field=models.CharField(
                choices=[
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="Completed",
                max_length=20,
            ),
        ),
        # Data migration: Update all "Planning" status values to "Planned"
        migrations.RunPython(migrate_planning_to_planned, reverse_planned_to_planning),
    ]
