# Generated by Django 5.2.11 on 2026-02-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0050_user_watch_provider_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_format",
            field=models.CharField(
                choices=[
                    ("Y-m-d", "2026-01-18 (ISO)"),
                    ("m/d/Y", "01/18/2026 (US, m/d/Y)"),
                    ("M j, Y", "Jan 18, 2026 (US, long)"),
                    ("d/m/Y", "18/01/2026 (EU, d/m/Y)"),
                    ("d.m.Y", "18.01.2026 (EU, d.m.Y)"),
                    ("d-m-Y", "18-01-2026 (EU, d-m-Y)"),
                    ("j M Y", "18 Jan 2026 (EU / UK, long)"),
                    ("j. F Y", "18. January 2026 (EU, full month)"),
                ],
                default="Y-m-d",
                help_text="Preferred date display format",
                max_length=20,
            ),
        ),
    ]
