# Generated by Django 5.2.11 on 2026-03-04 19:51

from django.db import migrations, models


def migrate_user_planning_to_planned(apps, schema_editor):
    """Update all user status preference fields from 'Planning' to 'Planned'."""
    User = apps.get_model('users', 'user')
    status_fields = [
        'anime_status', 'boardgame_status', 'book_status', 'comic_status',
        'game_status', 'list_detail_status', 'manga_status', 'movie_status',
        'season_status', 'tv_status'
    ]
    
    for field_name in status_fields:
        User.objects.filter(**{field_name: 'Planning'}).update(**{field_name: 'Planned'})


def reverse_user_planned_to_planning(apps, schema_editor):
    """Reverse: change user status preferences from 'Planned' back to 'Planning'."""
    User = apps.get_model('users', 'user')
    status_fields = [
        'anime_status', 'boardgame_status', 'book_status', 'comic_status',
        'game_status', 'list_detail_status', 'manga_status', 'movie_status',
        'season_status', 'tv_status'
    ]
    
    for field_name in status_fields:
        User.objects.filter(**{field_name: 'Planned'}).update(**{field_name: 'Planning'})


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0056_alter_anime_status_alter_basicmedia_status_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0050_user_watch_provider_region"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="tv_status_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="season_status_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="movie_status_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="anime_status_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="manga_status_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="game_status_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="book_status_valid",
        ),
        migrations.RemoveConstraint(
            model_name="user",
            name="list_detail_status_valid",
        ),
        migrations.AlterField(
            model_name="user",
            name="anime_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="boardgame_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="book_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="comic_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="game_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="list_detail_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="manga_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="movie_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="season_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="tv_status",
            field=models.CharField(
                choices=[
                    ("All", "All"),
                    ("Completed", "Completed"),
                    ("In progress", "In Progress"),
                    ("Planned", "Planned"),
                    ("Not Started", "Not Started"),
                    ("Paused", "Paused"),
                    ("Dropped", "Dropped"),
                ],
                default="All",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "list_detail_status__in",
                        [
                            "All",
                            "Completed",
                            "In progress",
                            "Planned",
                            "Not Started",
                            "Paused",
                            "Dropped",
                        ],
                    )
                ),
                name="list_detail_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "tv_status__in",
                        [
                            "All",
                            "Completed",
                            "In progress",
                            "Planned",
                            "Not Started",
                            "Paused",
                            "Dropped",
                        ],
                    )
                ),
                name="tv_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "season_status__in",
                        [
                            "All",
                            "Completed",
                            "In progress",
                            "Planned",
                            "Not Started",
                            "Paused",
                            "Dropped",
                        ],
                    )
                ),
                name="season_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "movie_status__in",
                        [
                            "All",
                            "Completed",
                            "In progress",
                            "Planned",
                            "Not Started",
                            "Paused",
                            "Dropped",
                        ],
                    )
                ),
                name="movie_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "anime_status__in",
                        [
                            "All",
                            "Completed",
                            "In progress",
                            "Planned",
                            "Not Started",
                            "Paused",
                            "Dropped",
                        ],
                    )
                ),
                name="anime_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "manga_status__in",
                        [
                            "All",
                            "Completed",
                            "In progress",
                            "Planned",
                            "Not Started",
                            "Paused",
                            "Dropped",
                        ],
                    )
                ),
                name="manga_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "game_status__in",
                        [
                            "All",
                            "Completed",
                            "In progress",
                            "Planned",
                            "Not Started",
                            "Paused",
                            "Dropped",
                        ],
                    )
                ),
                name="game_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "book_status__in",
                        [
                            "All",
                            "Completed",
                            "In progress",
                            "Planned",
                            "Not Started",
                            "Paused",
                            "Dropped",
                        ],
                    )
                ),
                name="book_status_valid",
            ),
        ),        
        # Data migration: Update all user status preference fields from "Planning" to "Planned"
        migrations.RunPython(migrate_user_planning_to_planned, reverse_user_planned_to_planning),
    ]
