# Generated by Django 5.2.11 on 2026-03-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0052_remove_user_tv_status_valid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="full_width_layout",
            field=models.BooleanField(
                default=False, help_text="Stretch content across the entire screen"
            ),
        ),
    ]
